// <auto-generated />
using System;
using Cards.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cards.Persistence.Migrations
{
    [DbContext(typeof(RepositoryDbContext))]
    [Migration("20240316092833_Change fields maximum length")]
    partial class Changefieldsmaximumlength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cards.Domain.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("AppUserId");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin46d-9e9f-44d3-8425-263ba67509aa",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "842d0d33-5555-4c18-b871-0dfb76e5ca46",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAECKxteV7I+hxq/qr/90e42nqzlneyDISf3onCtW5x6ZaJE8nxFt0I4FFOa/zNpGl5A==",
                            PhoneNumberConfirmed = false,
                            RoleId = "Adminf86-5601-41eb-a871-a660b2f0f449",
                            SecurityStamp = "62d2f7e1-fb47-424b-b7ec-3dc0ca839f45",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "kev5f943-112f-4d49-888d-c671e210b8b8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d696173e-c9e6-4a13-ba24-cf4b8e85acf1",
                            Email = "kev@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEMSt2T2eDIedgycUqPFqYRqIoH2eZ2XeegWYFdXp24jnCYXmiv7+AJ9cK1Y1Zv/fyg==",
                            PhoneNumberConfirmed = false,
                            RoleId = "Member8a-19f1-430e-aba5-9082dacfa9dd",
                            SecurityStamp = "ad3d9db9-ed10-4327-a77e-b500bf28f75d",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "suee8ebc-7959-4591-b86c-da19d3630419",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3a904fa3-2c26-4b1a-a921-0fc25b084c44",
                            Email = "sue@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEOKCenc0USRwMThcv4lXFUfV1iS7klRXC0eL+pX734TEcWCwP2q+qVa3LuqLmuX7FQ==",
                            PhoneNumberConfirmed = false,
                            RoleId = "Member8a-19f1-430e-aba5-9082dacfa9dd",
                            SecurityStamp = "9e866649-8cd9-4371-8e93-d75633a17b06",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "sam172c6-46e5-4b40-a0a7-54f2424c7791",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "26dc4482-4714-40bb-b63f-b84c1805107c",
                            Email = "sam@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEIyjJE3L3JvmUtL/nV2oA/au9qcDlQrX9adikRxRS731Xy4GupU5nClNCG+W7Tk9BQ==",
                            PhoneNumberConfirmed = false,
                            RoleId = "Member8a-19f1-430e-aba5-9082dacfa9dd",
                            SecurityStamp = "6a9e0bcb-c75e-40e8-9f8f-3ed7fd9cbb5d",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "ben8c400-aa14-4fb9-868e-1202d25bff95",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "582df46d-f661-4234-93b3-1522a51a9fc9",
                            Email = "ben@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEH8kLtLi/MpV/R47gNZiwIx2TDcrJMK8+psxmWb+Td8pnsD2Y7VBMMZ+ns/X9XTTbQ==",
                            PhoneNumberConfirmed = false,
                            RoleId = "Member8a-19f1-430e-aba5-9082dacfa9dd",
                            SecurityStamp = "eaa8b332-2e2c-40bc-8f4e-4b63941c26b2",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "elide650-28ea-4df1-bfc4-6b3e9a03d0de",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "df2fd2a5-e214-47b4-8db6-2c9399fce6f9",
                            Email = "elie@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEKVYcHQ1Qfd+END7C9iJArKPvUpjTjtUeFbl5/ckAKFPfCrH1huMg5rlHac/bCgz8A==",
                            PhoneNumberConfirmed = false,
                            RoleId = "Member8a-19f1-430e-aba5-9082dacfa9dd",
                            SecurityStamp = "fdc979ba-fd4d-4bd2-9ae3-fcde97240adb",
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("Cards.Domain.Entities.Card", b =>
                {
                    b.Property<string>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CardId");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.HasKey("CardId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("StatusId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            CardId = "fixbugs2-cd1d-43cd-b997-71a7f2a20096",
                            AppUserId = "kev5f943-112f-4d49-888d-c671e210b8b8",
                            Color = "#ADD8E6",
                            DateOfCreation = new DateTime(2024, 1, 20, 20, 37, 19, 0, DateTimeKind.Utc),
                            Description = "The system has bags to be fixed",
                            Name = "Fix bugs",
                            StatusId = "Todo343d-f8ec-4197-b0b2-f3365f71f2e2"
                        },
                        new
                        {
                            CardId = "systemInstallation-8fae-7488fc2c1b95",
                            AppUserId = "kev5f943-112f-4d49-888d-c671e210b8b8",
                            Color = "#FF7F50",
                            DateOfCreation = new DateTime(2024, 1, 15, 20, 37, 19, 0, DateTimeKind.Utc),
                            Description = "Installation of system to the new client.",
                            Name = "System Installation",
                            StatusId = "InProgress643-4e2e-bba7-8ebebb32d606"
                        },
                        new
                        {
                            CardId = "updateDatabase-f8a1-49e2-b7ab-2f5c6d73c93d",
                            AppUserId = "kev5f943-112f-4d49-888d-c671e210b8b8",
                            Color = "#32CD32",
                            DateOfCreation = new DateTime(2024, 2, 5, 15, 20, 0, 0, DateTimeKind.Utc),
                            Description = "Perform necessary updates on the database.",
                            Name = "Update Database",
                            StatusId = "InProgress643-4e2e-bba7-8ebebb32d606"
                        },
                        new
                        {
                            CardId = "clientMeeting-2f9e-4681-a499-4a2d1b2e36e4",
                            AppUserId = "kev5f943-112f-4d49-888d-c671e210b8b8",
                            Color = "#800080",
                            DateOfCreation = new DateTime(2024, 2, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Schedule a meeting with the client to discuss project updates.",
                            Name = "Client Meeting",
                            StatusId = "Todo343d-f8ec-4197-b0b2-f3365f71f2e2"
                        },
                        new
                        {
                            CardId = "updateDatabase-9c1f-4e7d-8737-d1f4e1ef5933",
                            AppUserId = "suee8ebc-7959-4591-b86c-da19d3630419",
                            Color = "#FFA500",
                            DateOfCreation = new DateTime(2024, 2, 20, 10, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Apply patches and optimize database performance.",
                            Name = "Update Database",
                            StatusId = "Todo343d-f8ec-4197-b0b2-f3365f71f2e2"
                        },
                        new
                        {
                            CardId = "clientMeeting-7c8a-4a7d-9533-56a21b5c92e1",
                            AppUserId = "suee8ebc-7959-4591-b86c-da19d3630419",
                            Color = "#4682B4",
                            DateOfCreation = new DateTime(2024, 2, 25, 14, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Discuss project milestones and deliverables with the client.",
                            Name = "Client Meeting",
                            StatusId = "InProgress643-4e2e-bba7-8ebebb32d606"
                        },
                        new
                        {
                            CardId = "clientMeeting-6c72-45fe-a7bf-4cd6d1d90c91",
                            AppUserId = "suee8ebc-7959-4591-b86c-da19d3630419",
                            Color = "#8A2BE2",
                            DateOfCreation = new DateTime(2024, 3, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Review project scope and timeline with the client.",
                            Name = "Client Meeting",
                            StatusId = "Todo343d-f8ec-4197-b0b2-f3365f71f2e2"
                        });
                });

            modelBuilder.Entity("Cards.Domain.Entities.CardStatus", b =>
                {
                    b.Property<string>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("StatusId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("StatusId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            StatusId = "Todo343d-f8ec-4197-b0b2-f3365f71f2e2",
                            Name = "ToDo"
                        },
                        new
                        {
                            StatusId = "InProgress643-4e2e-bba7-8ebebb32d606",
                            Name = "In Progress"
                        },
                        new
                        {
                            StatusId = "Done83ea-b4c1-4107-a66b-da86fcecf73f",
                            Name = "Done"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("RoleId");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RoleId")
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Cards.Domain.Entities.Role", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Role");

                    b.HasData(
                        new
                        {
                            Id = "Adminf86-5601-41eb-a871-a660b2f0f449",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = "Member8a-19f1-430e-aba5-9082dacfa9dd",
                            Name = "Member"
                        });
                });

            modelBuilder.Entity("Cards.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("Cards.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Cards.Domain.Entities.Card", b =>
                {
                    b.HasOne("Cards.Domain.Entities.AppUser", "AppUser")
                        .WithMany("Cards")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cards.Domain.Entities.CardStatus", "CardStatus")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("CardStatus");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Cards.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Cards.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cards.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Cards.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cards.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
